/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cjaun' at '6/10/17 7:59 PM' with Gradle 2.14.1
 *
 * @author cjaun, @date 6/10/17 7:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
